
package bp2_final;

import bp2_final.ShapePanel;
import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Lenovo
 */
public class RateUs extends javax.swing.JFrame {
  
    /**
     * Creates new form RateUs
     */
    public RateUs() {    
        initComponents();        
        ShapePanel panel = new ShapePanel();       
        this.add(panel);       
        this.pack();
               
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        panel3 = new javax.swing.JPanel();
        panel4 = new javax.swing.JPanel();
        panel5 = new javax.swing.JPanel();
        btn_rate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rate");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panel1.setPreferredSize(new java.awt.Dimension(120, 100));
        panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        panel2.setPreferredSize(new java.awt.Dimension(120, 100));
        panel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel3.setPreferredSize(new java.awt.Dimension(120, 100));
        panel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel4.setPreferredSize(new java.awt.Dimension(120, 100));
        panel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel5.setPreferredSize(new java.awt.Dimension(120, 100));
        panel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btn_rate.setText("Rate Us");
        btn_rate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_rate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(panel4, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(panel5, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(panel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(panel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(btn_rate)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_rateActionPerformed(java.awt.event.ActionEvent evt) {
        JOptionPane.showMessageDialog(this, "Thanks for your feedback!", "Info", JOptionPane.INFORMATION_MESSAGE);

    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {
        draw();
    }

    private void panel1MouseClicked(java.awt.event.MouseEvent evt) {
        Graphics2D g1 = (Graphics2D) panel1.getGraphics();
        Graphics2D g2 = (Graphics2D) panel2.getGraphics();
        Graphics2D g3 = (Graphics2D) panel3.getGraphics();
        Graphics2D g4 = (Graphics2D) panel4.getGraphics();
        Graphics2D g5 = (Graphics2D) panel5.getGraphics();

        int[] xPoints1 = {55, 67, 109, 73, 83, 55, 27, 37, 1, 43};
        int[] yPoints1 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g1.setColor(Color.BLACK);
        g1.drawPolygon(xPoints1, yPoints1, 10);
        g1.setColor(Color.YELLOW);
        g1.fillPolygon(xPoints1, yPoints1, yPoints1.length);
        int[] xPoints2 = {75, 87, 129, 93, 103, 75, 47, 57, 21, 63};
        int[] yPoints2 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g2.setColor(Color.BLACK);
        g2.drawPolygon(xPoints2, yPoints2, 10);
        g2.setColor(Color.WHITE);
        g2.fillPolygon(xPoints2, yPoints2, xPoints2.length);
        int[] xPoints3 = {95, 107, 149, 113, 123, 95, 67, 77, 41, 83};
        int[] yPoints3 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g3.setColor(Color.BLACK);
        g3.drawPolygon(xPoints3, yPoints3, 10);
        g3.setColor(Color.WHITE);
        g3.fillPolygon(xPoints3, yPoints3, xPoints3.length);
        int[] xPoints4 = {115, 127, 169, 133, 143, 115, 87, 97, 61, 103};
        int[] yPoints4 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g4.setColor(Color.BLACK);
        g4.drawPolygon(xPoints4, yPoints4, 10);
        g4.setColor(Color.WHITE);
        g4.fillPolygon(xPoints4, yPoints4, xPoints4.length);
        int[] xPoints5 = {135, 147, 189, 153, 163, 135, 107, 117, 81, 123};
        int[] yPoints5 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g5.setColor(Color.BLACK);
        g5.drawPolygon(xPoints5, yPoints5, 10);
        g5.setColor(Color.WHITE);
        g5.fillPolygon(xPoints5, yPoints5, xPoints5.length);
    }//GEN-LAST:event_panel1MouseClicked

    private void panel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2MouseClicked
        Graphics2D g1 = (Graphics2D) panel1.getGraphics();
        Graphics2D g2 = (Graphics2D) panel2.getGraphics();
        Graphics2D g3 = (Graphics2D) panel3.getGraphics();
        Graphics2D g4 = (Graphics2D) panel4.getGraphics();
        Graphics2D g5 = (Graphics2D) panel5.getGraphics();

        int[] xPoints1 = {55, 67, 109, 73, 83, 55, 27, 37, 1, 43};
        int[] yPoints1 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g1.setColor(Color.BLACK);
        g1.drawPolygon(xPoints1, yPoints1, 10);
        g1.setColor(Color.YELLOW);
        g1.fillPolygon(xPoints1, yPoints1, yPoints1.length);
        int[] xPoints2 = {75, 87, 129, 93, 103, 75, 47, 57, 21, 63};
        int[] yPoints2 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g2.setColor(Color.BLACK);
        g2.drawPolygon(xPoints2, yPoints2, 10);
        g2.setColor(Color.YELLOW);
        g2.fillPolygon(xPoints2, yPoints2, xPoints2.length);
        int[] xPoints3 = {95, 107, 149, 113, 123, 95, 67, 77, 41, 83};
        int[] yPoints3 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g3.setColor(Color.BLACK);
        g3.drawPolygon(xPoints3, yPoints3, 10);
        g3.setColor(Color.WHITE);
        g3.fillPolygon(xPoints3, yPoints3, xPoints3.length);
        int[] xPoints4 = {115, 127, 169, 133, 143, 115, 87, 97, 61, 103};
        int[] yPoints4 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g4.setColor(Color.BLACK);
        g4.drawPolygon(xPoints4, yPoints4, 10);
        g4.setColor(Color.WHITE);
        g4.fillPolygon(xPoints4, yPoints4, xPoints4.length);
        int[] xPoints5 = {135, 147, 189, 153, 163, 135, 107, 117, 81, 123};
        int[] yPoints5 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g5.setColor(Color.BLACK);
        g5.drawPolygon(xPoints5, yPoints5, 10);
        g5.setColor(Color.WHITE);
        g5.fillPolygon(xPoints5, yPoints5, xPoints5.length);
    }//GEN-LAST:event_panel2MouseClicked

    private void panel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel3MouseClicked
        Graphics2D g1 = (Graphics2D) panel1.getGraphics();
        Graphics2D g2 = (Graphics2D) panel2.getGraphics();
        Graphics2D g3 = (Graphics2D) panel3.getGraphics();
        Graphics2D g4 = (Graphics2D) panel4.getGraphics();
        Graphics2D g5 = (Graphics2D) panel5.getGraphics();

        int[] xPoints1 = {55, 67, 109, 73, 83, 55, 27, 37, 1, 43};
        int[] yPoints1 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g1.setColor(Color.BLACK);
        g1.drawPolygon(xPoints1, yPoints1, 10);
        g1.setColor(Color.YELLOW);
        g1.fillPolygon(xPoints1, yPoints1, yPoints1.length);
        int[] xPoints2 = {75, 87, 129, 93, 103, 75, 47, 57, 21, 63};
        int[] yPoints2 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g2.setColor(Color.BLACK);
        g2.drawPolygon(xPoints2, yPoints2, 10);
        g2.setColor(Color.YELLOW);
        g2.fillPolygon(xPoints2, yPoints2, xPoints2.length);
        int[] xPoints3 = {95, 107, 149, 113, 123, 95, 67, 77, 41, 83};
        int[] yPoints3 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g3.setColor(Color.BLACK);
        g3.drawPolygon(xPoints3, yPoints3, 10);
        g3.setColor(Color.YELLOW);
        g3.fillPolygon(xPoints3, yPoints3, xPoints3.length);
        int[] xPoints4 = {115, 127, 169, 133, 143, 115, 87, 97, 61, 103};
        int[] yPoints4 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g4.setColor(Color.BLACK);
        g4.drawPolygon(xPoints4, yPoints4, 10);
        g4.setColor(Color.WHITE);
        g4.fillPolygon(xPoints4, yPoints4, xPoints4.length);
        int[] xPoints5 = {135, 147, 189, 153, 163, 135, 107, 117, 81, 123};
        int[] yPoints5 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g5.setColor(Color.BLACK);
        g5.drawPolygon(xPoints5, yPoints5, 10);
        g5.setColor(Color.WHITE);
        g5.fillPolygon(xPoints5, yPoints5, xPoints5.length);
    }//GEN-LAST:event_panel3MouseClicked

    private void panel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel4MouseClicked
        Graphics2D g1 = (Graphics2D) panel1.getGraphics();
        Graphics2D g2 = (Graphics2D) panel2.getGraphics();
        Graphics2D g3 = (Graphics2D) panel3.getGraphics();
        Graphics2D g4 = (Graphics2D) panel4.getGraphics();
        Graphics2D g5 = (Graphics2D) panel5.getGraphics();

        int[] xPoints1 = {55, 67, 109, 73, 83, 55, 27, 37, 1, 43};
        int[] yPoints1 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g1.setColor(Color.BLACK);
        g1.drawPolygon(xPoints1, yPoints1, 10);
        g1.setColor(Color.YELLOW);
        g1.fillPolygon(xPoints1, yPoints1, yPoints1.length);
        int[] xPoints2 = {75, 87, 129, 93, 103, 75, 47, 57, 21, 63};
        int[] yPoints2 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g2.setColor(Color.BLACK);
        g2.drawPolygon(xPoints2, yPoints2, 10);
        g2.setColor(Color.YELLOW);
        g2.fillPolygon(xPoints2, yPoints2, xPoints2.length);
        int[] xPoints3 = {95, 107, 149, 113, 123, 95, 67, 77, 41, 83};
        int[] yPoints3 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g3.setColor(Color.BLACK);
        g3.drawPolygon(xPoints3, yPoints3, 10);
        g3.setColor(Color.YELLOW);
        g3.fillPolygon(xPoints3, yPoints3, xPoints3.length);
        int[] xPoints4 = {115, 127, 169, 133, 143, 115, 87, 97, 61, 103};
        int[] yPoints4 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g4.setColor(Color.BLACK);
        g4.drawPolygon(xPoints4, yPoints4, 10);
        g4.setColor(Color.YELLOW);
        g4.fillPolygon(xPoints4, yPoints4, xPoints4.length);
        int[] xPoints5 = {135, 147, 189, 153, 163, 135, 107, 117, 81, 123};
        int[] yPoints5 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g5.setColor(Color.BLACK);
        g5.drawPolygon(xPoints5, yPoints5, 10);
        g5.setColor(Color.WHITE);
        g5.fillPolygon(xPoints5, yPoints5, xPoints5.length);
    }//GEN-LAST:event_panel4MouseClicked

    private void panel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel5MouseClicked
        Graphics2D g1 = (Graphics2D) panel1.getGraphics();
        Graphics2D g2 = (Graphics2D) panel2.getGraphics();
        Graphics2D g3 = (Graphics2D) panel3.getGraphics();
        Graphics2D g4 = (Graphics2D) panel4.getGraphics();
        Graphics2D g5 = (Graphics2D) panel5.getGraphics();

        int[] xPoints1 = {55, 67, 109, 73, 83, 55, 27, 37, 1, 43};
        int[] yPoints1 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g1.setColor(Color.BLACK);
        g1.drawPolygon(xPoints1, yPoints1, 10);
        g1.setColor(Color.YELLOW);
        g1.fillPolygon(xPoints1, yPoints1, yPoints1.length);
        int[] xPoints2 = {75, 87, 129, 93, 103, 75, 47, 57, 21, 63};
        int[] yPoints2 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g2.setColor(Color.BLACK);
        g2.drawPolygon(xPoints2, yPoints2, 10);
        g2.setColor(Color.YELLOW);
        g2.fillPolygon(xPoints2, yPoints2, xPoints2.length);
        int[] xPoints3 = {95, 107, 149, 113, 123, 95, 67, 77, 41, 83};
        int[] yPoints3 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g3.setColor(Color.BLACK);
        g3.drawPolygon(xPoints3, yPoints3, 10);
        g3.setColor(Color.YELLOW);
        g3.fillPolygon(xPoints3, yPoints3, xPoints3.length);
        int[] xPoints4 = {115, 127, 169, 133, 143, 115, 87, 97, 61, 103};
        int[] yPoints4 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g4.setColor(Color.BLACK);
        g4.drawPolygon(xPoints4, yPoints4, 10);
        g4.setColor(Color.YELLOW);
        g4.fillPolygon(xPoints4, yPoints4, xPoints4.length);
        int[] xPoints5 = {135, 147, 189, 153, 163, 135, 107, 117, 81, 123};
        int[] yPoints5 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g5.setColor(Color.BLACK);
        g5.drawPolygon(xPoints5, yPoints5, 10);
        g5.setColor(Color.YELLOW);
        g5.fillPolygon(xPoints5, yPoints5, xPoints5.length);
    }//GEN-LAST:event_panel5MouseClicked

    void draw(){
        Graphics2D g1 = (Graphics2D) panel1.getGraphics();
        Graphics2D g2 = (Graphics2D) panel2.getGraphics();
        Graphics2D g3 = (Graphics2D) panel3.getGraphics();
        Graphics2D g4 = (Graphics2D) panel4.getGraphics();
        Graphics2D g5 = (Graphics2D) panel5.getGraphics();

        int[] xPoints1 = {55, 67, 109, 73, 83, 55, 27, 37, 1, 43};
        int[] yPoints1 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g1.setColor(Color.BLACK);
        g1.drawPolygon(xPoints1, yPoints1, 10);
        g1.setColor(Color.WHITE);
        g1.fillPolygon(xPoints1, yPoints1, yPoints1.length);
        int[] xPoints2 = {75, 87, 129, 93, 103, 75, 47, 57, 21, 63};
        int[] yPoints2 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g2.setColor(Color.BLACK);
        g2.drawPolygon(xPoints2, yPoints2, 10);
        g2.setColor(Color.WHITE);
        g2.fillPolygon(xPoints2, yPoints2, xPoints2.length);
        int[] xPoints3 = {95, 107, 149, 113, 123, 95, 67, 77, 41, 83};
        int[] yPoints3 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g3.setColor(Color.BLACK);
        g3.drawPolygon(xPoints3, yPoints3, 10);
        g3.setColor(Color.WHITE);
        g3.fillPolygon(xPoints3, yPoints3, xPoints3.length);
        int[] xPoints4 = {115, 127, 169, 133, 143, 115, 87, 97, 61, 103};
        int[] yPoints4 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g4.setColor(Color.BLACK);
        g4.drawPolygon(xPoints4, yPoints4, 10);
        g4.setColor(Color.WHITE);
        g4.fillPolygon(xPoints4, yPoints4, xPoints4.length);
        int[] xPoints5 = {135, 147, 189, 153, 163, 135, 107, 117, 81, 123};
        int[] yPoints5 = {40, 76, 76, 94, 136, 112, 136, 94, 76, 76};
        g5.setColor(Color.BLACK);
        g5.drawPolygon(xPoints5, yPoints5, 10);
        g5.setColor(Color.WHITE);
        g5.fillPolygon(xPoints5, yPoints5, xPoints5.length);
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        draw();
    }
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (Exception e) {
            e.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RateUs r = new RateUs();
                r.setLocationRelativeTo(null);
                r.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_rate;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JPanel panel5;
    // End of variables declaration//GEN-END:variables
}
